---
groups::group16::function6::prod::uuid1: '5c07f008-60d7-4afd-8c4c-a66a0a3d0748'

groups::group16::function6::prod::big_map:
  data1:
    ip1_1: '127.0.0.1'
    uuid2_1: 'c537493a-6cea-4179-a631-fb65153f29b6'
    uuid3_1: '151be68f-ad6e-4cad-8493-27e194e96585'
    uuid4_1: '9f5e2669-a086-438e-8227-1590550955c0'
  data2:
    ip1_1: '127.0.0.1'
    servers2:
      - 'foo1.mycompany.org'
      - 'foo2.mycompany.org'
      - 'foo3.mycompany.org'
      - 'foo4.mycompany.org'
    uuid3_1: '99becf97-9593-45f5-a78f-6274bd86fbfc'
    servers4:
      - 'foo1.mycompany.org'
      - 'foo2.mycompany.org'
      - 'foo3.mycompany.org'
      - 'foo4.mycompany.org'
      - 'foo5.mycompany.org'
      - 'foo6.mycompany.org'
      - 'foo7.mycompany.org'
      - 'foo8.mycompany.org'
      - 'foo9.mycompany.org'
  data3:
    uuid1_1: '9bdfb75f-3b96-4374-8760-be1380dad5d1'
    ips2:
      - '127.0.0.1'
      - '127.0.0.2'
      - '127.0.0.3'
      - '127.0.0.4'
      - '127.0.0.5'
      - '127.0.0.6'
      - '127.0.0.7'
      - '127.0.0.8'
      - '127.0.0.9'
      - '127.0.0.10'
      - '127.0.0.11'
    uuid3_1: '2ad6496d-5b9d-48d7-8fce-603480bc5dcd'
  data4:
    ips1:
      - '127.0.0.1'
      - '127.0.0.2'
      - '127.0.0.3'
      - '127.0.0.4'
      - '127.0.0.5'
      - '127.0.0.6'
      - '127.0.0.7'
      - '127.0.0.8'
      - '127.0.0.9'
      - '127.0.0.10'
      - '127.0.0.11'
    ip2_1: '127.0.0.1'
    uuid3_1: 'd44c31b2-97a8-4393-8916-25b64e83cd5a'
  data5:
    uuid1_1: 'b093af6b-56d9-4d15-b758-4f077fa20c6f'
    servers2:
      - 'foo1.mycompany.org'
      - 'foo2.mycompany.org'
      - 'foo3.mycompany.org'
      - 'foo4.mycompany.org'
      - 'foo5.mycompany.org'
      - 'foo6.mycompany.org'
    servers3:
      - 'foo1.mycompany.org'
      - 'foo2.mycompany.org'
      - 'foo3.mycompany.org'
      - 'foo4.mycompany.org'
      - 'foo5.mycompany.org'
      - 'foo6.mycompany.org'
      - 'foo7.mycompany.org'
      - 'foo8.mycompany.org'
      - 'foo9.mycompany.org'
      - 'foo10.mycompany.org'
      - 'foo11.mycompany.org'
    ip4_1: '127.0.0.1'
